httpPort=1337
xmppIp=127.0.0.1
xmppPort=5222
freeRoamUdpIp=127.0.0.1
freeRoamUdpPort=9999
raceUdpIp=127.0.0.1
raceUdpPort=9998
openFireToken=y0gs2EUWSakiz1q5

#choose your xmpp server type
xmppServerType=OpenFire
#xmppServerType=Offline

#choose your db driver
dbDriver=MySql
#dbDriver=H2